apiVersion: v1
baseDomain: ## DNS zone to use: redhat.local ##
compute:
- name: worker
  hyperthreading: Enabled
  platform:
    ovirt:
      cpu:
        cores: 4 ## CPU count for worker nodes
        sockets: 1
      memoryMB: 16384 ## RAM for worker ndoes
      osDisk:
        sizeGB: 40
      vmType: server
  replicas: 3
controlPlane:
  name: master
  platform:
    ovirt:
      cpu:
        cores: 4 ## CPU count for controlplane nodes
        sockets: 1 
      memoryMB: 16384 ## RAM for controlplane nodes
      osDisk:
        sizeGB: 40
      vmType: server
  replicas: 3
metadata:
  name: ## cluster name 
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14  ## Network that pods use
    hostPrefix: 23
  machineNetwork:
  - cidr: ## Enter network CIDR address 
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16 ## Network that Services use
platform:
  ovirt:
    api_vip: ## IP address api.<cluster_name>.<base_domain>
    ingress_vip: ## IP address of *.apps.<cluster_name>.<base_domain> 
    ovirt_cluster_id: ## ovirt cluster id ex: 058861da-6b2e-4491-b1c3-2d68b65740c9
    ovirt_network_name: ## name of network to use
    ovirt_storage_domain_id: ## ID of storage domain (GUID) ex: 21db2d98-f24f-4532-80b1-c23f1ee142a0
    vnicProfileID: ## ID of vnicProfileID ex: 4410c9bb-ae1f-4e85-a801-63ca9b4edfa0
publish: Internal
pullSecret: '{"auths":{"bastion.redhat.local:5000":{"auth":"123456789="}}}' ## Replace with your registry and credential  
imageContentSources:
- mirrors:
  - bastion.redhat.local:5000/openshift/release
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - bastion.redhat.local:5000/openshift/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADA......
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIFnzCCA4egAwIBAgIUb5wmeybqQeJv6Zi04zNPGMI737IwDQYJKoZIhvcNAQEL
  BQAwXzEaMBgGA1UEAwwRdXRpbGl0eS5yZWRoYXQuaW8xEDAOBgNVBAoMB1JlZCBI
  YXQxFTATBgNVBAcMDERlZmF1bHQgQ2l0eTELMAkGA1UECAwCVFgxCzAJBgNVBAYT
  < .... omitted .... >
  -----END CERTIFICATE-----