apiVersion: v1
baseDomain: ## DNS zone to use: redhat.local ##
credentialsMode: Mint  ## Mint == cluster managed, Passthrough == Uses install cred thru lifetime, Manual == you manage
controlPlane:
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      rootVolume:
        size: 250
        type: gp2
      type: m5.xlarge
  replicas: 3
compute:
- hyperthreading: Enabled
  name: worker
  platform:
    aws:
      rootVolume:
        size: 250
        type: gp2
      type: m5.xlarge
  replicas: 3
metadata:
  name: ##cluster_name: ocp, cluster, <customer_name>
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14   ## Network that Pods use
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16  ## Must enapsulate subnets defined below
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16   ## Service network 
platform:
  aws:
    serviceEndpoints:
    - name: ec2
      url: https://ec2.us-gov-west-1.amazonaws.com
    - name: elasticloadbalancing
      url: https://elasticloadbalancing.us-gov-west-1.amazonaws.com
    zones:
    - us-gov-west-1a
    - us-gov-west-1b
    - us-gov-west-1c
    region: us-gov-west-1
    subnets: ## List of private subnets - OR - If using public subnets, you must include the private subnets as well
      - subnet-1
      - subnet-2
      - subnet-3
    amiID: ami-0d993be65a4c274a8 ## AMI Id of the coreOS AMI in your region
pullSecret: '{"auths":{"bastion.redhat.local:5000":{"auth":"123456789="}}}' ## Replace with your registry and credential  
fips: true
sshKey: ssh-rsa AAAAB3NzaC1....   ## SSH Public Key ##
publish: Internal
imageContentSources:
- mirrors:
  - bastion.redhat.local:5000/openshift/release
  source: quay.io/openshift-release-dev/ocp-release
- mirrors:
  - bastion.redhat.local:5000/openshift/release
  source: quay.io/openshift-release-dev/ocp-v4.0-art-dev
additionalTrustBundle: |
  -----BEGIN CERTIFICATE-----
  MIIFnzCCA4egAwIBAgIUb5wmeybqQeJv6Zi04zNPGMI737IwDQYJKoZIhvcNAQEL
  BQAwXzEaMBgGA1UEAwwRdXRpbGl0eS5yZWRoYXQuaW8xEDAOBgNVBAoMB1JlZCBI
  YXQxFTATBgNVBAcMDERlZmF1bHQgQ2l0eTELMAkGA1UECAwCVFgxCzAJBgNVBAYT
  < .... omitted .... >
  -----END CERTIFICATE-----